# Generated by Django 2.2.6 on 2019-10-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProximoLancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('sinopse', models.CharField(max_length=500)),
                ('imagem', models.CharField(max_length=500)),
                ('nomeAbreviado', models.CharField(max_length=100)),
                ('dataInicioFinal', models.CharField(max_length=500)),
                ('temporadaDeLancamento', models.CharField(max_length=100)),
                ('diaHoraDeExibicao', models.CharField(max_length=100)),
                ('produtores', models.CharField(max_length=500)),
                ('licenciadores', models.CharField(max_length=500)),
                ('estudio', models.CharField(max_length=500)),
                ('midiaOriginal', models.CharField(max_length=500)),
                ('generos', models.CharField(max_length=500)),
            ],
        ),
    ]
