# Generated by Django 2.2.6 on 2019-12-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20191207_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
