# Generated by Django 2.2.6 on 2019-10-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('estilo', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
            ],
        ),
    ]
